branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - '2017.01'
  - latest
install:
  - rakudobrew build-panda
  - panda installdeps .
  #- zef install Bailador
  # "JSON::Tiny", "LWP::Simple" ],
