branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - latest
#  - 2015.09
install:
  - rakudobrew build-panda
  - panda install Template::Mojo
  - panda intsall HTTP::Easy
  - panda install JSON::Tiny
#  - panda install URI Template::Mojo HTTP::Easy Template::Mustache
